export const routes = {
  homePath: "/home",
  holidayPath: "/holidays",
  leaveRequestPath: "/leaverequest",
  approvedLeavesPath: "/approvedleaves",
  pendingLeavesPath: "/pendingleaves",
  rejectedLeavesPath: "/rejectedleaves",
  cancelledLeavesPath: "/cancelledleaves",
  manageLeaverequestPath: "/manageleaverequest",
  employeeListPath: "/employeelist",
  employeeLeavesListPath: "/employeeleaveslist",
  leaveReasonPath: "/leavereason",
  leaveTypePath: "/leavetype",
  departmentPath: "/department",
  forgotPasswordPath: "/forgotpassword",
  otpPath: "/otp",
  resetPasswordPath: "/resetpassword",
  dashboardPath: "/dashboard",
};
